### ISSUE TITLE
repository.nfo is all messed up

### ISSUE THREAD

**Issue by Grumbel** [SuperTux/addons#12]
The repository.nfo is all messed up. The way it is supposed to work:

* you change levels in `src/testlevels`
* you zip them up to `repository/testlevels_v2.zip` (increment version number by 1)
* you update the version tag, the url and the md5 in repository.nfo
* you *never* overwrite a file in `repository/`
* `index-0_3_5.nfo` follows different rules (no version tracking), at this point probably best to just ignore it

     (supertux-addoninfo
         (id "niso-yetis-revenge")
         (version 1)   <-- **This is important**
         (type "worldmap")
         (title "Yeti's Revenge")
         (author "niso")
         (license "GPL 2+ / CC-by-sa 3.0")
         (url "https://raw.githubusercontent.com/SuperTux/addons/master/repository/niso-yetis-    revenge_v1.zip") 
         (md5 "a33999163e1f78ed62064dade32bf37c")
        )

What happened instead: The URL didn't get change, but the underlying file was replaced. The md5 was changed as well, the version wasn't updated. 

Result: Game gets all confused, as it can no longer tell that a new version got released.

**Comment by tobbi** [comment]
I see! Sorry, we need a better way of updating the nfo file... I didn't know how this worked so I just assumed.

**Comment by LMH0013** [comment]
Actually I may have unwittingly done this, I'll see to getting it fixed.

**Comment by tobbi** [comment]
I think this was done by me, as I was fixing issues in Yeti's Revenge.

**Comment by LMH0013** [comment]
@tobbi No, you're fine.  You changed only the source files, which does nothing on the player side.  The repo (zip files) and index file needs to be changed in order for the addon manager to recognize changes.  I think when I updated the repo for 0.4.0 I somehow missed changing the version numbers before rebuilding the zip files and index.  I must have rushed it for release and only checked to make sure things at least worked (if not properly).  The good news is that once I correct the versions, your changes to Yeti's Revenge will now be in place.

**Comment by LMH0013** [comment]
This should all be cleared up as of commit 7358050.  I'm not sure how I let that happen, but I think the mess should work itself out now.
