### ISSUE TITLE
Please add simons world

### ISSUE THREAD

**Issue by Gangerl** [SuperTux/addons#21]
We have build a nice world called "Simon's World" with 18 levels overall. Please check it at http://lauffher.de/simon/
Perhaps you can put it here in the repo?

**Comment by manuel-st** [comment]
Hey, I packed your worldmap in the SuperTux addon format, so it can be easily opened in-game. Hope you don't mind that it is now uploaded to Github, too.
[simons_world.zip](https://github.com/SuperTux/addons/files/1968999/simons_world.zip)

**Comment by tobbi** [comment]
Upload for posterity: 
[simons_world.zip](https://github.com/SuperTux/addons/files/1969023/simons_world.zip)

**Comment by manuel-st** [comment]
I recommenend uploading your worldmap at the [SuperTux addon forum](https://forum.freegamedev.net/viewforum.php?f=66) first, as more people check it, imo. (Or at least I am checking it more often than Github).

Some quick tip (I didn't play through all of the levels yet): At least the first four levels are a bit too short.

**Comment by manuel-st** [comment]
Level "Klettere!": Add a hint for all non-germans that you can climb everywhere. Also, you cannot avoid getting hit by the spikes at the end of the level when you are big Tux.

Level "Labyrinth": Might be tricky to solve as big Tux.

OK, they are all a bit short and so no checkpoints are needed.

**Comment by Gangerl** [comment]
Thank you for the feedback. We will rework the world a little bit and upload it to the SuperTux addon forum. Then we come back :-)

**Comment by weluvgoatz** [comment]
finally
