### ISSUE TITLE
MD5 checksum errors for addon levels

### ISSUE THREAD

**Issue by 7wells** [SuperTux/addons#27]
Hello!

I run ST 0.5 on Android and get MD5 checksum errors for all addon levels when downloading them from within ST - with the exception of "Serano's Islands - Remastered", which can then be selected. But when clicking on it from the game menu, nothing happens.

What can I do to drill down the root cause of this problem?

Thanks for your help!

PS:
The last open issue is shown to be a year old. Is this repo still in active development at all?

**Comment by Ordoviz** [comment]
Your `supertux2/addons/repository.nfo` might be out-dated. Try selecting "Check online" in the addons menu.

Playing with a touch screen must be frustrating. I recommend the desktop version of SuperTux. The Android version is unofficial.

**Comment by 7wells** [comment]
I did check for updates first.
And no, I play on Amazon's Fire TV with connected game controllers. ST is really great on this device. Playing this and other similar games on a PC does not make sense to me. The kids (and us parents) love playing in the living room on the TV. ;-) Therefore, I would be so happy to get ST running on Android (understanding that there might be problems on Fire OS).
