### ISSUE TITLE
Update add-ons for 0.4.0

### ISSUE THREAD

**Issue by tobbi** [SuperTux/addons#5]
This includes:

- Updating add-ons to new versions which had source string issues 913ed411146aa478f3936b0e028cde2515d28484

- Adding language packs to the repository

**Comment by LMH0013** [comment]
Can I get some clarification?  It looks like 913ed41 has changed the source code of the addons to fix the string issues, but as I understand it those changes have not be integrated into the addons themselves.  So "updating add-ons" just consists of rebuilding the zip files and updating the version number so SuperTux recognizes them as new.  Is that correct?  Or do we need to go through all the addons and apply the new string format?

**Comment by Hume2** [comment]
By the way there are still some addons those aren't on transifex anyway.

**Comment by tobbi** [comment]
@LMH0013 Yes, that is correct. Even just updating the repo index, changing the hash of the zips in the lisp file will get them recognized as new afaik.

@Hume2: I'll try to take care of them!

**Comment by tobbi** [comment]
@Hume2 Before I add your levels, could you spellcheck your strings please? Check https://github.com/SuperTux/translations/blob/master/hume-worldmaps.pot for a list of them. Otherwise, translators will complain!

**Comment by LMH0013** [comment]
@tobbi Right-o, I'll take care of it then.
		
        
		
		 ---- On Tue, 24 Nov 2015 06:38:53 -1000  notifications@github.com  wrote ----@LMH0013 Yes, that is correct. Even just updating the repo index, changing the hash of the zips in the lisp file will get them recognized as new afaik.
@Hume2: I'll try to take care of them!

**Comment by tobbi** [comment]
I mean: Of course zip them, and check them in first ;)

**Comment by LMH0013** [comment]
Right, I actually noticed that the source and zip files had different hashes. Didn't want to mess with it until I knew why. Glad I know now.
		
        
		
		 ---- On Tue, 24 Nov 2015 07:03:53 -1000  notifications@github.com  wrote ----I mean: Of course zip them, and check them in first ;)

**Comment by LMH0013** [comment]
I've got all the addons updated to match their current source, so assuming that the language packs are all set (which they appear to be) this could probably be closed.

FYI, we probably need to go through all the addons to make sure they work properly-- there have been some recent changes to SuperTux which might affect how some of the addons work.  I wanted to check this as well, but have not had the time so it'll just have to be done step-by-step.
